### ISSUE TITLE
Upgraded to Fedora40, getting crashes in mediainfo

### ISSUE THREAD

**Issue by DurotarHeights** [MediaArea/MediaInfo#925]
I'm on Fedora 40, using mediainfo-24.04-1.fc40.x86_64 rpm. running mediainfo against this file crashes. (most mkvs do work, more than one does not. This example file plays fine and ffmpeg and mkvalidator don't show any errors in the mkv or the encoded stream.)

This is the gdb backtrace:

mediainfo -f file.mkv
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
#1  0x00007ffff7f72152 in ZenLib::Ztring::From_UTF8 (this=this@entry=0x7fffffffbe00, S=<optimized out>, Start=Start@entry=0, Length=Length@entry=18446744073709551615)
    at /usr/src/debug/libzen-0.4.41-4.fc40.x86_64/Source/ZenLib/Ztring.cpp:399
#2  0x00007ffff7cb3c35 in ZenLib::Ztring::From_UTF8 (this=<optimized out>, S=<optimized out>, Length=<optimized out>, this=<optimized out>, S=<optimized out>, Length=<optimized out>)
    at /usr/include/ZenLib/Ztring.h:91
#3  MediaInfoLib::File__Analyze::Fill(MediaInfoLib::stream_t, unsigned long, char const*, char const*, unsigned long, bool, bool) [clone .constprop.0] (this=0x5555556c6bf0,
    StreamKind=MediaInfoLib::Stream_Audio, StreamPos=0, Parameter=0x7ffff7d3c806 "dmixmod", Value=<optimized out>, Replace=false, Utf8=true, Value_Size=18446744073709551615)
    at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Project/CMake/../../Source/MediaInfo/File__Analyze.h:1153
#4  0x00007ffff7852073 in MediaInfoLib::File_Ac3::Streams_Fill (this=0x5555556c6bf0) at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/Audio/File_Ac3.cpp:1563
#5  0x00007ffff777502f in MediaInfoLib::File__Analyze::Fill (this=0x5555556c6bf0, ParserName_Char=<optimized out>) at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/File__Analyze.cpp:3074
#6  0x00007ffff7a625d5 in MediaInfoLib::File_Mk::Streams_Finish (this=<optimized out>) at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/Multiple/File_Mk.cpp:1057
#7  0x00007ffff777527a in MediaInfoLib::File__Analyze::ForceFinish (this=0x5555555d9fe0, ParserName_Char=<optimized out>)
    at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/File__Analyze.cpp:3178
#8  0x00007ffff776e99a in MediaInfoLib::File__Analyze::Open_Buffer_Finalize (this=0x5555555d9fe0, NoBufferModification=false)
    at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/File__Analyze.cpp:1332
#9  0x00007ffff78214a4 in MediaInfoLib::MediaInfo_Internal::Open_Buffer_Finalize (this=0x5555555cce20) at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/MediaInfo_Internal.cpp:1811
#10 0x00007ffff7beab33 in MediaInfoLib::Reader_File::Format_Test_PerParser_Continue (this=0x55555557ad90, MI=0x5555555cce20)
    at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/Reader/Reader_File.cpp:832
#11 0x00007ffff7bea113 in MediaInfoLib::Reader_File::Format_Test_PerParser (this=this@entry=0x55555557ad90, MI=MI@entry=0x5555555cce20,
    File_Name=L"file.mkv") at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/Reader/Reader_File.cpp:313
#12 0x00007ffff7bea944 in MediaInfoLib::Reader_File::Format_Test (this=this@entry=0x55555557ad90, MI=MI@entry=0x5555555cce20,
    File_Name=L"file.mkv") at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/Reader/Reader_File.cpp:225
#13 0x00007ffff781884d in MediaInfoLib::MediaInfo_Internal::Entry (this=0x5555555cce20) at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/MediaInfo_Internal.cpp:1416
#14 0x00007ffff7816e79 in MediaInfoLib::MediaInfo_Internal::Open (this=0x5555555cce20, File_Name_=L"file.mkv")
    at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/MediaInfo_Internal.cpp:1172
#15 0x00007ffff7827299 in MediaInfoLib::MediaInfoList_Internal::Entry (this=0x5555555cb3d0) at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/MediaInfoList_Internal.cpp:212
#16 0x00007ffff7820df8 in MediaInfoLib::MediaInfoList_Internal::Open (this=0x5555555cb3d0, File_Name=..., Options=<optimized out>)
    at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/MediaInfoList_Internal.cpp:148
#17 0x00007ffff782145c in MediaInfoLib::MediaInfoList::Open (this=<optimized out>, File=..., Options=<optimized out>) at /usr/src/debug/libmediainfo-24.04-1.fc40.x86_64/Source/MediaInfo/MediaInfoList.cpp:118
#18 0x0000555555557ae1 in Core::Menu_File_Open_Files_Continue (this=0x7fffffffdaa0, FileName=L"file.mkv") at ../../../Source/Common/Core.cpp:172
#19 main (argc=3, argv_ansi=<optimized out>) at ../../../Source/CLI/CLI_Main.cpp:155

**Comment by DurotarHeights** [comment]
Uupgraded to the current git  version and crashes stopped. please close
